/*
 * SPDX-FileCopyrightText: The LineageOS Project
 * SPDX-License-Identifier: Apache-2.0
 */

package org.lineageos.keyhandler

internal val REMOTE_APP_DEFAULT_TAGS = arrayOf("netflix", "primevideo", "disney", "hulu")

internal val REMOTE_APP_SKU_TAGS: Map<Int, Array<String?>> =
    mapOf(
        0x000a to arrayOf("netflix", "primevideo", "hbo", "psvue"),
        0x000b to arrayOf("netflix", "primevideo", "ctv", "crave"),
        0x000c to arrayOf("netflix", "primevideo", "zee5", "sony"),
        0x000d to arrayOf("netflix", "primevideo", "hbo", "psvue"),
        0x000e to arrayOf("netflix", "primevideo", "dazn", "tvnow"),
        0x000f to arrayOf("netflix", "primevideo", "livetv", "apps"),
        0x0010 to arrayOf("netflix", "primevideo", "dazn", "tvnow"),
        0x0011 to arrayOf("netflix", "primevideo", "zee5", "sony"),
        0x0012 to arrayOf("netflix", "primevideo", "hbo", "psvue"),
        0x0013 to arrayOf("netflix", "primevideo", "dazn", "tvnow"),
        0x0015 to arrayOf("netflix", "primevideo", "hbo", "hulu"),
        0x0016 to arrayOf("netflix", "primevideo", "hbo", "hulu"),
        0x0017 to arrayOf("netflix", "primevideo", "amazonmusic", "myfca"),
        0x001a to arrayOf("netflix", "primevideo", "hbo", "hulu"),
        0x0022 to arrayOf("netflix", "primevideo", "ctv", "crave"),
        0x0023 to arrayOf("netflix", "primevideo", "ctv", "crave"),
        0x0024 to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x0028 to arrayOf("netflix", "primevideo", "hbo", "hulu"),
        0x002c to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x002e to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x0035 to arrayOf("netflix", "primevideo", "livetv", "explorefvp"),
        0x0037 to arrayOf("netflix", "primevideo", "disney", "hulu"),
        0x0038 to arrayOf("netflix", "primevideo", "disney", "amazonmusic"),
        0x0039 to arrayOf("netflix", "primevideo", "dazn", "amazonmusic"),
        0x003a to arrayOf("netflix", "primevideo", "apps", "amazonmusic"),
        0x003b to arrayOf("netflix", "primevideo", "apps", "silk"),
        0x003c to arrayOf("netflix", "primevideo", "disney", "hulu"),
        0x0042 to arrayOf("netflix", "primevideo", "disney", "explorefvp"),
        0x0043 to arrayOf("netflix", "primevideo", "disney", "tvnow"),
        0x0044 to arrayOf("netflix", "primevideo", "disney", "apps"),
        0x0047 to arrayOf("netflix", "primevideo", "imdb", "hulu"),
        0x0048 to arrayOf("netflix", "primevideo", "dazn", "disney"),
        0x0049 to arrayOf("netflix", "primevideo", "dazn", "crave"),
        0x004e to arrayOf("netflix", "primevideo", "disney", "myfca"),
        0x004f to arrayOf("netflix", "primevideo", "disney", "download"),
        0x0050 to arrayOf("netflix", "primevideo", "download", "apps"),
        0x0051 to arrayOf("netflix", "primevideo", "download", "myfca"),
        0x0054 to arrayOf("netflix", "primevideo", "disney", "apps"),
        0x0055 to arrayOf("netflix", "primevideo", "dazn", "abema"),
        0x0056 to arrayOf("netflix", "primevideo", "amazonmusic", "abema"),
        0x0057 to arrayOf("netflix", "primevideo", "apps", "amazonmusic"),
        0x0058 to arrayOf("netflix", "primevideo", "disney", "amazonmusic"),
        0x0059 to arrayOf("netflix", "primevideo", "disney", "amazonmusic"),
        0x005a to arrayOf("netflix", "primevideo", "abema", "amazonmusic"),
        0x0060 to arrayOf("netflix", "primevideo", "directv", "peacock"),
        0x0061 to arrayOf("netflix", "primevideo", "tver", "abema"),
        0x0062 to arrayOf("netflix", "primevideo", "tver", "unext"),
        0x0064 to arrayOf("netflix", "primevideo", "apps", "sky"),
        0x0065 to arrayOf("netflix", "primevideo", "disney", "peacock"),
        0x0066 to arrayOf("netflix", "primevideo", "amazonmusic", "opappfreely"),
        0x0069 to arrayOf("netflix", "primevideo", "disney", "peacock"),
        0x006a to arrayOf("netflix", "primevideo", "directv", "peacock"),
        0x006b to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x006c to arrayOf("netflix", "primevideo", "amazonmusic", "explorefvp"),
        0x006d to arrayOf("netflix", "primevideo", "silk", "apps"),
        0x006e to arrayOf("netflix", "primevideo", "apps", "explorefvp"),
        0x006f to arrayOf("netflix", "primevideo", "tver", "unext"),
        0x0071 to arrayOf("netflix", "primevideo", "apps", "amazonmusic"),
        0x0072 to arrayOf("netflix", "primevideo", "apps", "sky"),
        0x0073 to arrayOf("netflix", "primevideo", "apps", "silk"),
        0x0074 to arrayOf("netflix", "primevideo", "amazonmusic", "explorefvp"),
        0x0075 to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x011a to arrayOf("netflix", "primevideo", "amazonmusic", "apps"),
        0x0125 to arrayOf("netflix", "primevideo", "apps", "opappfreely"),
        0x021a to arrayOf("netflix", "primevideo", "tver", "unext", null, "hulu", "abema", "disney", "youtube", "myviera"),
        0x021b to arrayOf("netflix", "primevideo", "disney", "youtube", null, "amazonmusic", "apps"),
        0x021c to arrayOf("netflix", "primevideo", "disney", "youtube", null, "amazonmusic", "apps"),
        0x021d to arrayOf("netflix", "primevideo", "directv", "peacock"),
        0x021e to arrayOf("netflix", "primevideo", "disney", "youtube", null, "freely", "apps"),
        0x021f to arrayOf("netflix", "primevideo", "disney", "youtube", null, "amazonmusic", "apps"),
        0x0220 to arrayOf("netflix", "primevideo", "disney", "amazonmusic", null, "tvplus", "apps"),
        0x0221 to arrayOf("netflix", "primevideo", "apps", "amazonmusic"),
        0x0222 to arrayOf("netflix", "primevideo", "opappfreely", "apps"),
    )
